# Numpy


## 📌 What is NumPy?
- NumPy is a Python library used for **numerical computing**.
- It provides support for **multi-dimensional arrays** and **efficient mathematical operations**.
- Core feature: the **ndarray** (N-dimensional array).
- Faster and more memory-efficient than native Python lists.

### Installing Numpy

In [ ]:
%pip install numpy #is the notebook-aware way to install packages

OR

In [ ]:
!pip install numpy # This might install outside the current Jupyter environment

## Creating Arrays

In [ ]:
import numpy as np

# From a list
a = np.array([1, 2, 3])
print("Variable A: ", a)

# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array \n", b)

#Useful for creating placeholders
print(f"\n ZEROS {np.zeros((2, 3))} \n")

#Common in initializing weights in neural networks (before training begins).
print(f"ONES {np.ones((3, 3))} \n")

#For creating sequences of numbers with specific intervals.
print(f"\n  ARRANGE {np.arange(0, 10, 2)} \n")

#ideal for graphing and interpolation.
print(f"LINSPACE {np.linspace(0, 1, 5)}")

Variable A:  [1 2 3]
2D Array 
 [[1 2 3]
 [4 5 6]]

 ZEROS [[0. 0. 0.]
 [0. 0. 0.]] 

ONES [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 


  ARRANGE [0 2 4 6 8] 

LINSPACE [0.   0.25 0.5  0.75 1.  ]


## Array Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

# Scalar Product
scalar = np.dot(a, b)
print(scalar)

mean = np.mean(a)
print("MEAN value of array A is: ", mean)

std = np.std(a)
print("STD value of array A is: ", std)

sum = np.sum(a)
print("SUM value of array A is: ", sum)

[5 7 9]
[ 4 10 18]
32
MEAN value of array A is:  2.0
STD value of array A is:  0.816496580927726
SUM value of array A is:  6


## Indexing and Slicing

In [ ]:
a = np.array([10, 20, 30, 40])
# print(a[1])
# print(a[1:3])


b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print("Accessing value on first array: ", b[0, 2])

print(b[:, 2])

[[1 2 3]
 [4 5 6]]
Accessing value on first array:  3
[3 6]


## Broadcasting

In [ ]:
a = np.array([1, 2, 3])
print(a + 2)

[3 4 5]


## Pratical Examples

In [ ]:
# Temperature Conversion
celsius = np.array([0, 20, 40])
fahrenheit = celsius * 9/5 + 32
print("Celsius to fahrenheit: ", fahrenheit)

Celsius to fahrenheit:  [ 32.  68. 104.]


In [ ]:
# Random Numbers

print(np.random.rand(5))

[0.04628554 0.0848717  0.70194822 0.63422427 0.17164856]


### Creating a 3X3 identity Matrix

In [ ]:
identity_matrix = np.eye(3)
print(f"3X3 Identity Matrix: \n", identity_matrix)

3X3 Identity Matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Generate 100 random number and find their mean and standard deviation

In [ ]:
random_numbers = np.random.rand(100)
mean = np.mean(random_numbers)
std_dev = np.std(random_numbers)

print("\nGenerated 100 random numbers:")
print(random_numbers)
print(f"\nMean: {mean}")
print(f"Standard Deviation: {std_dev}")


Generated 100 random numbers:
[0.656238   0.26624172 0.89300179 0.63220518 0.17554142 0.31233854
 0.44320315 0.30979523 0.94187727 0.68977986 0.50698644 0.84011205
 0.85978653 0.83205196 0.07726296 0.34497939 0.78001109 0.84147228
 0.64624306 0.8966149  0.11140934 0.24783332 0.21248595 0.9109626
 0.64451583 0.83740281 0.97976415 0.16749601 0.28523612 0.44567537
 0.91819005 0.58129861 0.87042197 0.73989009 0.06102486 0.78680317
 0.88186328 0.77212652 0.00206431 0.62164463 0.82082318 0.89905814
 0.97786894 0.21115934 0.6064154  0.64007162 0.18656151 0.60796385
 0.02268699 0.87824564 0.91489893 0.83705126 0.49437275 0.79858545
 0.01343407 0.40200658 0.50683668 0.9809499  0.23868435 0.01768728
 0.30616996 0.23343579 0.96812481 0.70707504 0.3785578  0.56743382
 0.00418587 0.53890013 0.21168098 0.05699943 0.78149677 0.12580804
 0.23389579 0.93232875 0.56258813 0.29113848 0.37639052 0.52384451
 0.80575819 0.49401611 0.51076594 0.72263542 0.64997605 0.15564899
 0.88286181 0.00211842 0.7364977

# ❓ Why Use NumPy Instead of Plain Python?

| Feature             | Python Lists         | NumPy Arrays         |
|---------------------|----------------------|----------------------|
| Speed               | Slow                 | Very fast            |
| Syntax              | Verbose              | Clean & vectorized   |
| Multi-Dimensional   | Awkward              | Easy and native      |
| Math Functions      | Manual / custom      | Built-in             |
| Memory Use          | High                 | Efficient            |


## Speed Comparison

In [ ]:
import time
# Python way
a = list(range(1_000_000)) # 1_000_000 is 1 million
start = time.time()
b = [x * 2 for x in a]
print("Python List: ", time.time() - start)

#Numpy
a = np.arange(1_000_000)
start = time.time()
b = a * 2
print("NumPy:", time.time() - start)

Python List:  0.05382347106933594
NumPy: 0.014894962310791016


# Cleaner Syntax

In [ ]:
# Python
a = [1, 2, 3]
b = [x + 5 for x in a]

# NumPy
a = np.array([1, 2, 3])
b = a + 5

## Memory Efficient

In [ ]:
import sys

py_list = list(range(1000000))
np_array = np.arange(1000000)

print(sys.getsizeof(py_list))   # Larger
print(np_array.nbytes)

8000056
8000000
